# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from core.api import action_pb2 as action__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in action_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ActionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Trigger = channel.unary_unary(
            "/swarmclone.action.ActionService/Trigger",
            request_serializer=action__pb2.TriggerRequest.SerializeToString,
            response_deserializer=action__pb2.TriggerResponse.FromString,
            _registered_method=True,
        )
        self.GetMapping = channel.unary_unary(
            "/swarmclone.action.ActionService/GetMapping",
            request_serializer=action__pb2.GetMappingRequest.SerializeToString,
            response_deserializer=action__pb2.ActionMapping.FromString,
            _registered_method=True,
        )
        self.ListMappings = channel.unary_unary(
            "/swarmclone.action.ActionService/ListMappings",
            request_serializer=action__pb2.ListMappingsRequest.SerializeToString,
            response_deserializer=action__pb2.ListMappingsResponse.FromString,
            _registered_method=True,
        )
        self.AddMapping = channel.unary_unary(
            "/swarmclone.action.ActionService/AddMapping",
            request_serializer=action__pb2.AddMappingRequest.SerializeToString,
            response_deserializer=action__pb2.AddMappingResponse.FromString,
            _registered_method=True,
        )
        self.RemoveMapping = channel.unary_unary(
            "/swarmclone.action.ActionService/RemoveMapping",
            request_serializer=action__pb2.RemoveMappingRequest.SerializeToString,
            response_deserializer=action__pb2.RemoveMappingResponse.FromString,
            _registered_method=True,
        )


class ActionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Trigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMappings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Trigger": grpc.unary_unary_rpc_method_handler(
            servicer.Trigger,
            request_deserializer=action__pb2.TriggerRequest.FromString,
            response_serializer=action__pb2.TriggerResponse.SerializeToString,
        ),
        "GetMapping": grpc.unary_unary_rpc_method_handler(
            servicer.GetMapping,
            request_deserializer=action__pb2.GetMappingRequest.FromString,
            response_serializer=action__pb2.ActionMapping.SerializeToString,
        ),
        "ListMappings": grpc.unary_unary_rpc_method_handler(
            servicer.ListMappings,
            request_deserializer=action__pb2.ListMappingsRequest.FromString,
            response_serializer=action__pb2.ListMappingsResponse.SerializeToString,
        ),
        "AddMapping": grpc.unary_unary_rpc_method_handler(
            servicer.AddMapping,
            request_deserializer=action__pb2.AddMappingRequest.FromString,
            response_serializer=action__pb2.AddMappingResponse.SerializeToString,
        ),
        "RemoveMapping": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveMapping,
            request_deserializer=action__pb2.RemoveMappingRequest.FromString,
            response_serializer=action__pb2.RemoveMappingResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "swarmclone.action.ActionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("swarmclone.action.ActionService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ActionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Trigger(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.action.ActionService/Trigger",
            action__pb2.TriggerRequest.SerializeToString,
            action__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMapping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.action.ActionService/GetMapping",
            action__pb2.GetMappingRequest.SerializeToString,
            action__pb2.ActionMapping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMappings(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.action.ActionService/ListMappings",
            action__pb2.ListMappingsRequest.SerializeToString,
            action__pb2.ListMappingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddMapping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.action.ActionService/AddMapping",
            action__pb2.AddMappingRequest.SerializeToString,
            action__pb2.AddMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveMapping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.action.ActionService/RemoveMapping",
            action__pb2.RemoveMappingRequest.SerializeToString,
            action__pb2.RemoveMappingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
