# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x11swarmclone.config\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"N\n\x0b\x43onfigValue\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x12\n\nvalue_type\x18\x04 \x01(\t\"<\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nvalue_type\x18\x03 \x01(\t\"/\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x0fValidateRequest\x12\x13\n\x0b\x63onfig_json\x18\x01 \x01(\t\"C\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\x12\x10\n\x08warnings\x18\x03 \x03(\t\"!\n\rExportRequest\x12\x10\n\x08sections\x18\x01 \x03(\t\"-\n\nConfigData\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"C\n\rImportRequest\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\toverwrite\x18\x03 \x01(\x08\"J\n\x0eImportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0eimported_count\x18\x03 \x01(\x05\x32\x8a\x03\n\rConfigService\x12\x44\n\x03Get\x12\x1d.swarmclone.config.GetRequest\x1a\x1e.swarmclone.config.ConfigValue\x12\x44\n\x03Set\x12\x1d.swarmclone.config.SetRequest\x1a\x1e.swarmclone.config.SetResponse\x12S\n\x08Validate\x12\".swarmclone.config.ValidateRequest\x1a#.swarmclone.config.ValidateResponse\x12I\n\x06\x45xport\x12 .swarmclone.config.ExportRequest\x1a\x1d.swarmclone.config.ConfigData\x12M\n\x06Import\x12 .swarmclone.config.ImportRequest\x1a!.swarmclone.config.ImportResponseB)Z\'github.com/hmr-BH/SwarmClone/api/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/hmr-BH/SwarmClone/api/config'
  _globals['_GETREQUEST']._serialized_start=35
  _globals['_GETREQUEST']._serialized_end=60
  _globals['_CONFIGVALUE']._serialized_start=62
  _globals['_CONFIGVALUE']._serialized_end=140
  _globals['_SETREQUEST']._serialized_start=142
  _globals['_SETREQUEST']._serialized_end=202
  _globals['_SETRESPONSE']._serialized_start=204
  _globals['_SETRESPONSE']._serialized_end=251
  _globals['_VALIDATEREQUEST']._serialized_start=253
  _globals['_VALIDATEREQUEST']._serialized_end=291
  _globals['_VALIDATERESPONSE']._serialized_start=293
  _globals['_VALIDATERESPONSE']._serialized_end=360
  _globals['_EXPORTREQUEST']._serialized_start=362
  _globals['_EXPORTREQUEST']._serialized_end=395
  _globals['_CONFIGDATA']._serialized_start=397
  _globals['_CONFIGDATA']._serialized_end=442
  _globals['_IMPORTREQUEST']._serialized_start=444
  _globals['_IMPORTREQUEST']._serialized_end=511
  _globals['_IMPORTRESPONSE']._serialized_start=513
  _globals['_IMPORTRESPONSE']._serialized_end=587
  _globals['_CONFIGSERVICE']._serialized_start=590
  _globals['_CONFIGSERVICE']._serialized_end=984
# @@protoc_insertion_point(module_scope)
