# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from core.api import config_pb2 as config__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in config_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
            "/swarmclone.config.ConfigService/Get",
            request_serializer=config__pb2.GetRequest.SerializeToString,
            response_deserializer=config__pb2.ConfigValue.FromString,
            _registered_method=True,
        )
        self.Set = channel.unary_unary(
            "/swarmclone.config.ConfigService/Set",
            request_serializer=config__pb2.SetRequest.SerializeToString,
            response_deserializer=config__pb2.SetResponse.FromString,
            _registered_method=True,
        )
        self.Validate = channel.unary_unary(
            "/swarmclone.config.ConfigService/Validate",
            request_serializer=config__pb2.ValidateRequest.SerializeToString,
            response_deserializer=config__pb2.ValidateResponse.FromString,
            _registered_method=True,
        )
        self.Export = channel.unary_unary(
            "/swarmclone.config.ConfigService/Export",
            request_serializer=config__pb2.ExportRequest.SerializeToString,
            response_deserializer=config__pb2.ConfigData.FromString,
            _registered_method=True,
        )
        self.Import = channel.unary_unary(
            "/swarmclone.config.ConfigService/Import",
            request_serializer=config__pb2.ImportRequest.SerializeToString,
            response_deserializer=config__pb2.ImportResponse.FromString,
            _registered_method=True,
        )


class ConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Import(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=config__pb2.GetRequest.FromString,
            response_serializer=config__pb2.ConfigValue.SerializeToString,
        ),
        "Set": grpc.unary_unary_rpc_method_handler(
            servicer.Set,
            request_deserializer=config__pb2.SetRequest.FromString,
            response_serializer=config__pb2.SetResponse.SerializeToString,
        ),
        "Validate": grpc.unary_unary_rpc_method_handler(
            servicer.Validate,
            request_deserializer=config__pb2.ValidateRequest.FromString,
            response_serializer=config__pb2.ValidateResponse.SerializeToString,
        ),
        "Export": grpc.unary_unary_rpc_method_handler(
            servicer.Export,
            request_deserializer=config__pb2.ExportRequest.FromString,
            response_serializer=config__pb2.ConfigData.SerializeToString,
        ),
        "Import": grpc.unary_unary_rpc_method_handler(
            servicer.Import,
            request_deserializer=config__pb2.ImportRequest.FromString,
            response_serializer=config__pb2.ImportResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "swarmclone.config.ConfigService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("swarmclone.config.ConfigService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.config.ConfigService/Get",
            config__pb2.GetRequest.SerializeToString,
            config__pb2.ConfigValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Set(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.config.ConfigService/Set",
            config__pb2.SetRequest.SerializeToString,
            config__pb2.SetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Validate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.config.ConfigService/Validate",
            config__pb2.ValidateRequest.SerializeToString,
            config__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Export(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.config.ConfigService/Export",
            config__pb2.ExportRequest.SerializeToString,
            config__pb2.ConfigData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Import(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.config.ConfigService/Import",
            config__pb2.ImportRequest.SerializeToString,
            config__pb2.ImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
