# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from core.api import system_pb2 as system__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in system_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
            "/swarmclone.system.SystemService/Start",
            request_serializer=system__pb2.StartRequest.SerializeToString,
            response_deserializer=system__pb2.StartResponse.FromString,
            _registered_method=True,
        )
        self.Stop = channel.unary_unary(
            "/swarmclone.system.SystemService/Stop",
            request_serializer=system__pb2.StopRequest.SerializeToString,
            response_deserializer=system__pb2.StopResponse.FromString,
            _registered_method=True,
        )
        self.Restart = channel.unary_unary(
            "/swarmclone.system.SystemService/Restart",
            request_serializer=system__pb2.RestartRequest.SerializeToString,
            response_deserializer=system__pb2.RestartResponse.FromString,
            _registered_method=True,
        )
        self.GetStatus = channel.unary_unary(
            "/swarmclone.system.SystemService/GetStatus",
            request_serializer=system__pb2.StatusRequest.SerializeToString,
            response_deserializer=system__pb2.SystemStatus.FromString,
            _registered_method=True,
        )
        self.GetServiceStatus = channel.unary_unary(
            "/swarmclone.system.SystemService/GetServiceStatus",
            request_serializer=system__pb2.ServiceStatusRequest.SerializeToString,
            response_deserializer=system__pb2.ServiceStatus.FromString,
            _registered_method=True,
        )


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Restart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Start": grpc.unary_unary_rpc_method_handler(
            servicer.Start,
            request_deserializer=system__pb2.StartRequest.FromString,
            response_serializer=system__pb2.StartResponse.SerializeToString,
        ),
        "Stop": grpc.unary_unary_rpc_method_handler(
            servicer.Stop,
            request_deserializer=system__pb2.StopRequest.FromString,
            response_serializer=system__pb2.StopResponse.SerializeToString,
        ),
        "Restart": grpc.unary_unary_rpc_method_handler(
            servicer.Restart,
            request_deserializer=system__pb2.RestartRequest.FromString,
            response_serializer=system__pb2.RestartResponse.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=system__pb2.StatusRequest.FromString,
            response_serializer=system__pb2.SystemStatus.SerializeToString,
        ),
        "GetServiceStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetServiceStatus,
            request_deserializer=system__pb2.ServiceStatusRequest.FromString,
            response_serializer=system__pb2.ServiceStatus.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "swarmclone.system.SystemService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("swarmclone.system.SystemService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.system.SystemService/Start",
            system__pb2.StartRequest.SerializeToString,
            system__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Stop(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.system.SystemService/Stop",
            system__pb2.StopRequest.SerializeToString,
            system__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Restart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.system.SystemService/Restart",
            system__pb2.RestartRequest.SerializeToString,
            system__pb2.RestartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.system.SystemService/GetStatus",
            system__pb2.StatusRequest.SerializeToString,
            system__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetServiceStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swarmclone.system.SystemService/GetServiceStatus",
            system__pb2.ServiceStatusRequest.SerializeToString,
            system__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
